
package lsmapp.instrPanels;

/**
 *
 * @author glos
 */
public class InstrPanel extends javax.swing.JPanel
{

    /** Creates new form InstrPanel */
    public InstrPanel(SpecificInstrPanel specificPanel, String instrName)
    {
        initComponents();
        this.instrName = instrName;
        this.specificPanel = specificPanel;
        this.barriersPanel = new BarriersPanel();
        instrNameLabel.setText(instrName);
        splitPane.setLeftComponent(specificPanel);
        splitPane.setRightComponent(barriersPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        instrNameLabel = new javax.swing.JLabel();

        splitPane.setDividerLocation(250);

        instrNameLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        instrNameLabel.setText("InstrName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(instrNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instrNameLabel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables


    private String instrName;
    private SpecificInstrPanel specificPanel;
    private BarriersPanel barriersPanel;
}
