
package lsmapp.instrPanels;

import finance.parameters.BarrierParams;
import finance.parameters.PartialBarrierParams;
import java.util.Collection;
import lsmapp.Pricer;

/**
 *
 * @author Grzegorz Los
 */
public class NewBarrierDialog extends javax.swing.JDialog
{
    /** Creates new form NewBarrierDialog */
    public NewBarrierDialog(Collection<String> assetNames, String initialName)
    {
        super(Pricer.getApp(), true);
        initComponents();
        putAssetNamesToCombo(assetNames, initialName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        offOrOnGroup = new javax.swing.ButtonGroup();
        OK = new javax.swing.JButton();
        cance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uai = new javax.swing.JRadioButton();
        uao = new javax.swing.JRadioButton();
        dai = new javax.swing.JRadioButton();
        dao = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        level = new javax.swing.JSpinner();
        partial = new javax.swing.JCheckBox();
        partialPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        since = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        until = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        barrierOff = new javax.swing.JRadioButton();
        barrierOn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        assetCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        cance.setText("Cancel");
        cance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Adding Barrier");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Barrier type:");

        typeGroup.add(uai);
        uai.setSelected(true);
        uai.setText("Up-and-in");

        typeGroup.add(uao);
        uao.setText("Up-and-out");

        typeGroup.add(dai);
        dai.setText("Down-and-in");

        typeGroup.add(dao);
        dao.setText("Down-and-out");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Level:");

        level.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        partial.setText("partial");
        partial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partialActionPerformed(evt);
            }
        });

        partialPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        partialPanel.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Since time:");

        since.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Until time:");

        until.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("barrier is ");

        offOrOnGroup.add(barrierOff);
        barrierOff.setSelected(true);
        barrierOff.setText("Off");

        offOrOnGroup.add(barrierOn);
        barrierOn.setText("On");

        javax.swing.GroupLayout partialPanelLayout = new javax.swing.GroupLayout(partialPanel);
        partialPanel.setLayout(partialPanelLayout);
        partialPanelLayout.setHorizontalGroup(
            partialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(partialPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barrierOff)
                        .addGap(18, 18, 18)
                        .addComponent(barrierOn))
                    .addGroup(partialPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(since, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(until, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        partialPanelLayout.setVerticalGroup(
            partialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(until, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(partialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(barrierOff)
                    .addComponent(barrierOn))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel7.setText("On asset:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cance, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(partial, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dai)
                                        .addGap(18, 18, 18)
                                        .addComponent(dao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uai)
                                        .addGap(31, 31, 31)
                                        .addComponent(uao))
                                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)))
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(221, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(assetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uai)
                    .addComponent(uao)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dai)
                    .addComponent(dao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(partial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(cance)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void canceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceActionPerformed
    setVisible(false);
}//GEN-LAST:event_canceActionPerformed

private void partialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partialActionPerformed
    partialPanel.setEnabled(partial.isSelected());
}//GEN-LAST:event_partialActionPerformed

private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
    OK_hit = true;
    setVisible(false);
}//GEN-LAST:event_OKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JComboBox assetCombo;
    private javax.swing.JRadioButton barrierOff;
    private javax.swing.JRadioButton barrierOn;
    private javax.swing.JButton cance;
    private javax.swing.JRadioButton dai;
    private javax.swing.JRadioButton dao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner level;
    private javax.swing.ButtonGroup offOrOnGroup;
    private javax.swing.JCheckBox partial;
    private javax.swing.JPanel partialPanel;
    private javax.swing.JSpinner since;
    private javax.swing.ButtonGroup typeGroup;
    private javax.swing.JRadioButton uai;
    private javax.swing.JRadioButton uao;
    private javax.swing.JSpinner until;
    // End of variables declaration//GEN-END:variables

    static BarrierWrapper showNewBarrierDialog(Collection<String> assetNames, String initialAsset)
    {
        NewBarrierDialog dialog = new NewBarrierDialog(assetNames, initialAsset);
        dialog.setVisible(true);
        BarrierWrapper bw;
        if (dialog.OK_hit)
            bw = dialog.makeBarrierWrapper();
        else
            bw = null;
        dialog.dispose();
        return bw;
    }

    private BarrierWrapper makeBarrierWrapper()
    {
        BarrierParams bp = makeBarrierParams();
        String asset = "" + assetCombo.getSelectedItem();
        if (partial.isSelected())
            return new BarrierWrapper( makePartialBarrierParams(bp), asset );
        else return new BarrierWrapper(bp, asset);        
    }

    private BarrierParams makeBarrierParams()
    {
        BarrierParams.Type type;
        if (uai.isSelected()) type = BarrierParams.Type.UAI;
        else if (uao.isSelected()) type = BarrierParams.Type.UAO;
        else if (dai.isSelected()) type = BarrierParams.Type.DAI;
        else type = BarrierParams.Type.DAO;
        double v = (Double) level.getValue();
        return new BarrierParams(type, v);
    }
    
    private PartialBarrierParams makePartialBarrierParams(BarrierParams bp)
    {
        double s = (Double) since.getValue();
        double u = (Double) until.getValue();
        PartialBarrierParams.Modification mod = barrierOff.isSelected() ?
                PartialBarrierParams.Modification.OFF : PartialBarrierParams.Modification.ON;
        return new PartialBarrierParams(bp, mod, s, u);
    }

    private void putAssetNamesToCombo(Collection<String> assetNames, String initialName)
    {
        for(String name: assetNames)
            assetCombo.addItem(name);
        assetCombo.setSelectedItem(initialName);
    }
    
    private boolean OK_hit;
    private String selectedAsset;
}
