
package lsmapp.methodPanels;

import java.awt.BorderLayout;
import lsmapp.instrPanels.InstrManager;

/**
 *
 * @author Grzegorz Los
 */
public class NewTaskTab extends javax.swing.JPanel
{

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        containerOfProgressesContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        containerOfNewTaskPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jSplitPane1.setDividerLocation(400);

        containerOfProgressesContainer.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Running tasks");
        containerOfProgressesContainer.add(jLabel1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setRightComponent(containerOfProgressesContainer);

        containerOfNewTaskPanel.setPreferredSize(new java.awt.Dimension(300, 391));
        containerOfNewTaskPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add new task");
        containerOfNewTaskPanel.add(jLabel2, java.awt.BorderLayout.NORTH);

        jSplitPane1.setLeftComponent(containerOfNewTaskPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerOfNewTaskPanel;
    private javax.swing.JPanel containerOfProgressesContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables


    /** Creates new form NewTaskTab */
    public NewTaskTab(InstrManager instrManager)
    {
        initComponents();
        prepareProgressContainer();
        prepareNewTasksPanel(instrManager);
        revalidate();
    }

    private void prepareProgressContainer()
    {
        progressesContainer = new ProgressesContainer();
        containerOfProgressesContainer.add(progressesContainer, BorderLayout.CENTER);
    }

    private void prepareNewTasksPanel(InstrManager instrManager)
    { 
        newTasksPanel = new NewTaskPanel(instrManager, progressesContainer);
        containerOfNewTaskPanel.add(newTasksPanel, BorderLayout.CENTER);
    }
    
    private NewTaskPanel newTasksPanel;
    private ProgressesContainer progressesContainer;
}
